### ISSUE TITLE
new module?

### ISSUE THREAD

**Issue by myhellone** [syepes/network_exporter#13]
Hi!

I want add module like in blackbox_exporter
for example some like this:

  ```
http_2xx_test:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]  # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_body_matches_regexp:
        - "Could not connect to database"
      fail_if_body_not_matches_regexp:
       - "Database OK"
      tls_config:
          insecure_skip_verify: false
```

How to do it in proper way?
